{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Values.serviceAccount.name }}
  {{- with .Values.serviceAccount }}
  labels: 
  {{- toYaml .labels | nindent 4 }}
  {{- end }}  
  annotations: 
  {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{ end }}