{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-sample-app-svc
  name: {{ .Release.Name }}-sample-app-svc
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port | default 8080 }}
    protocol: TCP
    targetPort: {{ .Values.image.port | default 8080 }}
  selector:
    app: {{ .Release.Name }}-sample-app
status:
  loadBalancer: {}
{{- end -}}
